<a href="https://colab.research.google.com/github/janjib/DataScienceLondonCompetition/blob/main/Project_1_Simple_Linear_Regression_on_Local_Chicken_Production_according_to_year.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib as pyplot
import pandas as pd

In [3]:
df = pd.read_csv("chicken_price_dataset.csv")
df.head()

Year  Chicken Population (Number)  \
0  2000                    123841122   
1  2001                    148990824   
2  2002                    170395132   
3  2003                    183345888   
4  2004                    191655949   

   Local Production of Chicken Meat - Quantity (Tonne)  \
0                                             628558     
1                                             674564     
2                                             752787     
3                                             756439     
4                                             816191     

   Local Production of Chicken Meat - (RM Million)  \
0                                           2581.7   
1                                           2696.7   
2                                           3085.4   
3                                           3321.2   
4                                           3638.9   

   Imports of Chicken Meat - Quantity (Tonne)  \
0                                       35118   
1                                       40043   
2                                       54183   
3                                       42427   
4                                       17367   

   Imports of Chicken Meat - (RM Million)  Imports of Live Chicken - Quantity  \
0                                   178.7                               20058   
1                                   199.6                               45966   
2                                   284.0                               64640   
3                                   197.4                              100109   
4                                    99.8                               11179   

   Imports of Live Chicken - (RM Million)  \
0                                     0.8   
1                                     0.4   
2                                     1.0   
3                                     0.7   
4                                     0.4   

   Exports of Poultry Meat - Quantity (Tonne)  \
0                                        6717   
1                                        9430   
2                                       12911   
3                                       14540   
4                                       10807   

   Exports of Poultry Meat - (RM Million)  
0                                    37.2  
1                                    63.0  
2                                    98.2  
3                                   115.1  
4                                   102.6

In [4]:
pd.isnull(df)

Year  Chicken Population (Number)  \
0   False                        False   
1   False                        False   
2   False                        False   
3   False                        False   
4   False                        False   
5   False                        False   
6   False                        False   
7   False                        False   
8   False                        False   
9   False                        False   
10  False                        False   
11  False                        False   
12  False                        False   
13  False                        False   
14  False                        False   
15  False                        False   
16  False                        False   
17  False                        False   
18  False                        False   
19  False                        False   

    Local Production of Chicken Meat - Quantity (Tonne)  \
0                                               False     
1                                               False     
2                                               False     
3                                               False     
4                                               False     
5                                               False     
6                                               False     
7                                               False     
8                                               False     
9                                               False     
10                                              False     
11                                              False     
12                                              False     
13                                              False     
14                                              False     
15                                              False     
16                                              False     
17                                              False     
18                                              False     
19                                              False     

    Local Production of Chicken Meat - (RM Million)  \
0                                             False   
1                                             False   
2                                             False   
3                                             False   
4                                             False   
5                                             False   
6                                             False   
7                                             False   
8                                             False   
9                                             False   
10                                            False   
11                                            False   
12                                            False   
13                                            False   
14                                            False   
15                                            False   
16                                            False   
17                                            False   
18                                            False   
19                                            False   

    Imports of Chicken Meat - Quantity (Tonne)  \
0                                        False   
1                                        False   
2                                        False   
3                                        False   
4                                        False   
5                                        False   
6                                        False   
7                                        False   
8                                        False   
9                                        False   
10                                       False   
11                                       False   
12                                       False   
13                        

In [15]:
dataset = df.iloc[:,[0,2]]
dataset.head()

Year  Local Production of Chicken Meat - Quantity (Tonne)
0  2000                                             628558  
1  2001                                             674564  
2  2002                                             752787  
3  2003                                             756439  
4  2004                                             816191

In [16]:
x = dataset.iloc[:,:-1].values
x

array([[2000],
       [2001],
       [2002],
       [2003],
       [2004],
       [2005],
       [2006],
       [2007],
       [2008],
       [2009],
       [2010],
       [2011],
       [2012],
       [2013],
       [2014],
       [2015],
       [2016],
       [2017],
       [2018],
       [2019]])

In [17]:
y = dataset.iloc[:,-1].values
y

array([ 628558,  674564,  752787,  756439,  816191,  862444,  911172,
        968000, 1023062, 1057760, 1140128, 1174334, 1223188, 1297703,
       1511763, 1551141, 1676246, 1598258, 1587539, 1589081])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
x_train

array([[2010],
       [2017],
       [2006],
       [2013],
       [2004],
       [2002],
       [2005],
       [2014],
       [2009],
       [2007],
       [2016],
       [2011],
       [2003],
       [2000],
       [2015],
       [2012]])

In [20]:
y_train

array([1140128, 1598258,  911172, 1297703,  816191,  752787,  862444,
       1511763, 1057760,  968000, 1676246, 1174334,  756439,  628558,
       1551141, 1223188])

In [21]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [25]:
def predictor(year):
  prediction = regressor.predict([[year]])
  return f"The local production of chicken meat on {year} is {prediction}"

predictor(2012)

'The local production of chicken meat on 2012 is [1304833.93632075]'